apiVersion: v1
kind: Service
metadata:
  name: jenkins2
  namespace: kube-devops
  labels:
    app: jenkins2
spec:
  selector:
    app: jenkins2
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: web
    nodePort: 40001
  - name: agent
    port: 50000
    targetPort: agent
    nodePort: 40002

